import { useEffect, useMemo, useState } from 'react';
import { Edit3, Plus, Search, Trash2, UsersRound, X, RefreshCw } from 'lucide-react';
import { useOutletContext } from 'react-router-dom';
import type { AppOutletContext } from '../layouts/AppLayout';
import { createCari, deleteCari, loadCari, loadModuleBranches, money, updateCari, type CariRow, type ModuleBranch } from '../lib/app';

const pick=(r:CariRow, keys:string[], fallback='')=>{for(const k of keys)if(r[k]!==undefined&&r[k]!==null&&String(r[k])!=='')return String(r[k]);return fallback};
const amount=(r:CariRow)=>Number(r.miktar??0)||0;
export function CariPage(){
 const {user}=useOutletContext<AppOutletContext>();
 const [rows,setRows]=useState<CariRow[]>([]),[branches,setBranches]=useState<ModuleBranch[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState<CariRow|null|undefined>(undefined),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const [c,b]=await Promise.all([loadCari(user),loadModuleBranches(user)]);setRows(c);setBranches(b)}catch(e){setError(e instanceof Error?e.message:'Cari kayıtları alınamadı.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user]);
 const list=useMemo(()=>rows.filter(r=>`${pick(r,['firma'])} ${pick(r,['aciklama'])} ${pick(r,['sube'])}`.toLocaleLowerCase('tr-TR').includes(q.toLocaleLowerCase('tr-TR'))),[rows,q]);
 const balance=rows.reduce((s,r)=>s+amount(r),0);
 if(loading)return <div className="loading-panel">Gerçek cari hesaplar yükleniyor...</div>;
 if(error)return <div className="error-panel"><strong>Cari hesaplar alınamadı</strong><p>{error}</p><button className="primary" onClick={load}><RefreshCw size={16}/> Tekrar dene</button></div>;
 return <div><div className="page-title"><div><div className="eyebrow">FİNANS · CARİ</div><h1>Cari Hesaplar</h1><p>Müşteri ve tedarikçi hareketlerini gerçek Supabase kayıtlarıyla yönetin.</p></div><button className="primary" onClick={()=>setModal(null)}><Plus size={17}/> Yeni cari hareket</button></div>
 <div className="module-summary"><div><span>Hareket</span><strong>{list.length}</strong></div><div><span>Net bakiye</span><strong>{money(list.reduce((s,r)=>s+amount(r),0))}</strong></div><div><span>Alacak</span><strong>{money(list.filter(r=>amount(r)>0).reduce((s,r)=>s+amount(r),0))}</strong></div><div><span>Borç</span><strong>{money(Math.abs(list.filter(r=>amount(r)<0).reduce((s,r)=>s+amount(r),0)))}</strong></div></div>
 <section className="panel module-panel"><div className="module-tools"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Firma, açıklama veya şube ara..."/></div><button className="secondary" onClick={load}><RefreshCw size={16}/> Yenile</button></div>{!list.length?<div className="empty-module"><div className="empty-icon"><UsersRound/></div><h3>Cari hareket bulunamadı</h3><p>Yeni cari hareket ekleyerek başlayabilirsiniz.</p></div>:<div className="table-wrap"><table><thead><tr><th>Firma</th><th>Şube</th><th>Tür</th><th>Açıklama</th><th>Tarih</th><th className="right">Bakiye</th><th/></tr></thead><tbody>{list.map((r,i)=>{const a=amount(r);return <tr key={String(r.id??i)}><td><strong>{pick(r,['firma'],'Firma')}</strong></td><td>{pick(r,['sube'],'Şube')}</td><td><span className={`badge ${a>=0?'success':'danger'}`}>{a>=0?'Alacak':'Borç'}</span></td><td>{pick(r,['aciklama'],'—')}</td><td>{pick(r,['tarih','islem_zamani'],'—')}</td><td className={`right amount ${a>=0?'income':'expense'}`}>{money(Math.abs(a))}</td><td className="right"><button className="icon-btn inline" title="Düzenle" onClick={()=>setModal(r)}><Edit3 size={16}/></button><button className="icon-btn inline" title="Pasifleştir" onClick={async()=>{if(!confirm('Bu cari hareket pasifleştirilsin mi?'))return;try{await deleteCari(String(r.id));await load()}catch(e){alert(e instanceof Error?e.message:'Cari hareket pasifleştirilemedi.')}}}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>}</section>{modal!==undefined&&<CariModal row={modal} branches={branches} saving={saving} user={user} onClose={()=>setModal(undefined)} onSave={async input=>{setSaving(true);try{if(modal?.id)await updateCari(String(modal.id),input,user);else await createCari(input,user);setModal(undefined);await load()}catch(e){alert(e instanceof Error?e.message:'Cari kaydedilemedi.')}finally{setSaving(false)}}}/>}</div>
}
function CariModal({row,branches,saving,user,onClose,onSave}:{row:CariRow|null;branches:ModuleBranch[];saving:boolean;user:AppOutletContext['user'];onClose:()=>void;onSave:(i:{branch_id:string;firma:string;miktar:number;aciklama:string;tarih:string;islem_turu:'Alacak'|'Borç'})=>Promise<void>}){const [branch,setBranch]=useState(pick(row||{},['branch_id'],user.branchIds[0]||branches[0]?.id||''));const [firma,setFirma]=useState(pick(row||{},['firma']));const [raw,setRaw]=useState(String(Math.abs(Number(row?.miktar??0))||''));const [type,setType]=useState<'Alacak'|'Borç'>(Number(row?.miktar??0)<0?'Borç':'Alacak');const [desc,setDesc]=useState(pick(row||{},['aciklama']));const [date,setDate]=useState(pick(row||{},['tarih']).slice(0,10)||new Date().toISOString().slice(0,10));return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><div className="eyebrow">CARİ HAREKET</div><h2>{row?'Düzenle':'Yeni cari hareket'}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label>Şube<select value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Firma<input value={firma} onChange={e=>setFirma(e.target.value)} placeholder="Müşteri / tedarikçi"/></label><label>İşlem türü<select value={type} onChange={e=>setType(e.target.value as 'Alacak'|'Borç')}><option>Alacak</option><option>Borç</option></select></label><label>Tutar<input type="number" min="0.01" step="0.01" value={raw} onChange={e=>setRaw(e.target.value)}/></label><label>Tarih<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Açıklama<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Vazgeç</button><button className="primary" disabled={saving} onClick={()=>onSave({branch_id:branch,firma,miktar:Number(raw),aciklama:desc,tarih:date,islem_turu:type})}>{saving?'Kaydediliyor...':'Kaydet'}</button></div></div></div>}
